/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminMetrics {
  'totalMedia' : bigint,
  'visitCount' : bigint,
  'totalCapsules' : bigint,
  'totalNotes' : bigint,
  'totalUsers' : bigint,
  'totalNeuronEntries' : bigint,
}
export interface Beneficiary {
  'id' : string,
  'username' : string,
  'displayName' : string,
  'createdAt' : Time,
  'hashedPassword' : string,
}
export interface Document {
  'id' : string,
  'title' : string,
  'documentType' : DocumentType,
  'createdAt' : Time,
  'updatedAt' : Time,
  'blobId' : string,
}
export type DocumentType = { 'pdf' : null } |
  { 'word' : null } |
  { 'excel' : null } |
  { 'powerpoint' : null };
export interface Media {
  'id' : string,
  'title' : string,
  'createdAt' : Time,
  'blobId' : string,
  'mediaType' : MediaType,
}
export type MediaType = { 'video' : null } |
  { 'photo' : null };
export interface NeuronEntry {
  'dissolveDate' : string,
  'notes' : string,
  'neuronId' : string,
  'designatedController' : string,
  'votingPreferences' : string,
}
export interface Note {
  'id' : string,
  'title' : string,
  'body' : string,
  'createdAt' : Time,
  'updatedAt' : Time,
}
export type Time = bigint;
export interface UserProfile { 'name' : string, 'email' : [] | [string] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addBeneficiary' : ActorMethod<[string, string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'beneficiaryLogin' : ActorMethod<[Principal, string, string], string>,
  'beneficiaryLogout' : ActorMethod<[string], undefined>,
  'createCapsule' : ActorMethod<[], undefined>,
  'createDoc' : ActorMethod<[string, string, DocumentType], Document>,
  'createMedia' : ActorMethod<[string, string, MediaType], string>,
  'createNeuronEntry' : ActorMethod<
    [string, string, string, string, string],
    string
  >,
  'createNote' : ActorMethod<[string, string], string>,
  'deleteCapsule' : ActorMethod<[], undefined>,
  'deleteDoc' : ActorMethod<[string], undefined>,
  'deleteMedia' : ActorMethod<[string], undefined>,
  'deleteNeuronEntry' : ActorMethod<[string], undefined>,
  'deleteNote' : ActorMethod<[string], undefined>,
  'getAdminMetrics' : ActorMethod<[], AdminMetrics>,
  'getBeneficiaries' : ActorMethod<[], Array<Beneficiary>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCanisterId' : ActorMethod<[], Principal>,
  'getCapsuleDocs' : ActorMethod<[], Array<Document>>,
  'getCapsuleLockStatus' : ActorMethod<[Principal], boolean>,
  'getCapsuleMedia' : ActorMethod<[Principal], Array<Media>>,
  'getCapsuleNotes' : ActorMethod<[Principal], Array<Note>>,
  'getCycleBalance' : ActorMethod<[], bigint>,
  'getGlobalInstructions' : ActorMethod<[Principal], string>,
  'getNeuronEntries' : ActorMethod<[Principal], Array<NeuronEntry>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isAdminSetup' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isLoggedInToBeneficiarySession' : ActorMethod<[string], boolean>,
  'recordVisit' : ActorMethod<[], undefined>,
  'removeBeneficiary' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setGlobalInstructions' : ActorMethod<[string], undefined>,
  'setupFirstAdmin' : ActorMethod<[], undefined>,
  'toggleCapsuleLock' : ActorMethod<[], undefined>,
  'updateDoc' : ActorMethod<[string, string], Document>,
  'updateNeuronEntry' : ActorMethod<
    [string, string, string, string, string, string],
    undefined
  >,
  'updateNote' : ActorMethod<[string, string, string], undefined>,
  'validateBeneficiarySession' : ActorMethod<[string], [] | [Principal]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];